const itemList = {
        "Drinks": [
            "BIB pepsi", 
            "BIB diet pepsi", 
            "BIB 7up", 
            "BIB Mountain dew", 
            "BIB Root beer", 
            "BIB 7up", 
            "BIB brisk iced tea", 
            "BIB lemonade", 
            "BIB ginger ale", 
            "BTL Pepsi", 
            "BTL Diet pepsi",
            "BTL Pepsi zero", 
            "BTL 7UP", 
            "BTL Ginger ale", 
            "BTL Root beer", 
            "BTL brisk iced tea", 
            "BTL Aquafina", 
            "CAN Pepsi",
            "CAN Diet Pepsi",
            "CAN Ginger Ale",
            "CAN Bubly Cherry",
            "CAN Bubly Blackberry",
            "CAN Shweppes Tonic Water",
            "CAN Montellier",
            "Clamato juice", 
            "Apple juice [Dine In]", 
            "Orange juice [Dine In]", 
            "Cranberry juice [Dine In]", 
            "Dole apple juice", 
            "Dole orange juice", 
            "Kids Apple juice", 
            "Grenadine syrup",
            "Pure Leaf Iced tea",
        ],
        "Sauces": [
            "Smokey BBQ sauce",
            "Honey garlic sauce",
            "Sweet & spicy thai sauce", 
            "Teriyaki sauce",
            "Hot sauce", 
            "Mild sauce", 
            "Medium sauce", 
            "Italian sauce",
            "Apple sauce",
            "Plum sauce [dine in]",
            "Cranberry sauce",
            "Worcestershire sauce", 
            "Ketchup bottles [dine in]",
            "Mighty caesar dressing [dine in]",
            "Caramel topping",
            "Chocolate topping", 
            "Coleslaw dressing [dine in]", 
            "Mayonnaise [dine in]",
            "Chalet dressing [dine in]", 
            "Sour cream 4L [dine in]",
            "Ketchup portions", 
            "Plum sauce portions", 
            "BBQ sauce portions", 
            "Mayonnaise portions",
            "Mighty caesar dressing portions",
            "Chalet dressing portions", 
            "Italian dressing portions", 
            "Balsamic vinaigrette dressing portions", 
            "Sour cream portions", 
            "Butter pots",  
            "Garlic butter spread", 
            "Margarine bucket",
            "Pickle Bucket",
            "Relish",
        ],
        "Boxes": [
            "Ala carte boxes", 
            "Entree boxes", 
            "Hot side boxes", 
            "Ala carte liners", 
            "Entree liners",
            "Side salad boxes (24oz)", 
            "Big salad boxes (43oz)", 
            "32oz bowl", 
            "12oz bowl [paper container]", 
            "8oz cups", 
            "3.5oz cups",
            "2oz cups", 
            "1oz cups",
            "32oz lids", 
            "12oz/8oz lids", 
            "3.5oz/2oz lids", 
            "1oz lids",
            "Paper bags large [Swiss Chalet printed]", 
            "Paper bags medium",
            "Paper bags small [Grocery bag]", 
            "Bowl holders", 
            "3 in 1 cutlery set", 
            "Soup spoons", 
            "Kids cups", 
            "Kids cups lids", 
            "Straws",
            "Pot pie containers",
            "VIRO Saran wrap",
            "Aluminium foil",
        ],
        "Perishables": [
            "Lettuce romaine", 
            "Lettuce chopped",
            "Lettuce leaf crown", 
            "Heritage blend", 
            "Coleslaw cabbage", 
            "Shredded carrots", 
            "Tomatoes", 
            "Red onions", 
            "Spring onions",
            "Broccoli",
            "Cauliflower", 
            "Bell Pepper",
            "Celery",
            "Lemons", 
            "Cucumbers", 
            "Jumbo fries potatoes", 
            "Baked potatoes",
            "Shredded cheese pub mix",
            "Parmesan Shaved cheese",
            "Cheddar cheese slices",
            "Swiss cheese slices",
            "Cheese curds",
        ],
        "Frozen": [
            "Pork Ribs", 
            "Naked Wings", 
            "Chicken Tenders", 
            "Perogies", 
            "Crispy sandwich", 
            "Green beans", 
            "Sweet potato fries", 
            "Mashed potatoes", 
            "Pot pie mix", 
            "Mini donuts",
            "Apple pie", 
            "Coconut pie", 
            "Lemon pie", 
            "Cheese cake", 
            "Molten lava cake", 
            "Spring rolls sheets",
            "Tortilla 12”", 
            "Ace buns 4”",
            "Kids buns 3.5”",
            "Dinner rolls", 
            "Hoagie rolls", 
            "White bread", 
            "Beef burgers",
            "Mini burgers", 
            "Veggie burgers", 
            "Kids pizza", 
            "Kids mac and cheese balls", 
            "Whipped cream", 
            "Pot pie lids sheet 36 Qt.",
            "Bacon Chips",
            "Bacon Strips",
        ],
        "Seasonings": [
            "Chalet seasoning",
            "Steak spice seasoning", 
            "Garlic Mesquite seasoning",
            "Cajun seasoning", 
            "Cinnamon sugar", 
            "Sprinkles", 
            "Oreo crunch",
            "Salt portions", 
            "Pepper portions", 
            "Greek seasoning",
            "Pepper jar"
        ],
        "Cook": [
            "Chicken totes", 
            "Chalet seasoning mix", 
            "Gravy mix",
            "Chicken soup mix", 
            "Rice pilaf seasoning", 
            "Rice", 
            "Salt", 
            "Kids Noodles",
            "Broccoli Soup",
        ],
        "Chemicals": [
                "Degreaser",
                "dishwasher Liquid: Ultra 5 Gallon",
                "Sanitizer",
                "Fryer cleaner Chemical",
                "Handwashing Soap",
                "Hand Sanitizer",
                "Dual Action Mop Liquid",
                "garbage bags large (35 x 50)",
                "garbage bags small",
                "Paper: Handwash towels",
                "Paper: Bathroom tissues",
                "Mop head Red",
                "Mop head Green",
                "Combitherm",
                "Ecoshine"
        ],
        "Other": [
            "Tea bags", 
            "Coffee", 
            "Decaf coffee",
            "Cotton candy",
            "Oreo Crunch",
            "Milkettes",
            "Creamers", 
            "Milk",
            "Chocolate milk", 
            "Sugar",
            "Salt portions",
            "Pepper portions", 
            "Sweetener", 
            "Crackers", 
            "Croutons", 
            "M & Ms", 
            "Kids toys",
            "Napkins",
            "Swiss chalet napkins"
        ],
        "LTO": [
            "Stuffing mix", 
            "Pumpkin pie", 
            "Beef",
            "Horseraddish sauce",
            "Beef Au Jus Mix",
        ],
    };
